options.platform.name=Android
options.automation.name=UiAutomator2
options.device.name=emulator-5554
options.app.activity=.MainActivity

#protected property for override by chose app
options.app.package="com.vk.vkvideo"
options.app.package.vkvideo=com.vk.vkvideo
options.app.package.alchemy=com.ilyin.alchemy

options.no.reset=false
options.full.reset=false

options.new.command.timeout=300

appium.server.url=http://127.0.0.1:4723
