options.platform.name=Android
options.platform.version=14
options.automation.name=UiAutomator2
options.device.name=emulator-5554

#protected properties for override by chose app (current default value)
options.app.package=com.vk.vkvideo
options.app.activity=com.vk.video.screens.main.MainActivity
#chose app in test
options.app.package.vkvideo=com.vk.vkvideo
options.app.activity.vkvideo=com.vk.video.screens.main.MainActivity
options.app.activity.alchemy=com.ilyin.app_google_core.GoogleAppActivity
options.app.package.alchemy=com.ilyin.alchemy

options.no.reset=false
options.full.reset=false

options.new.command.timeout=300

appium.server.url=http://127.0.0.1:4723

selenide.configuration.timeout = 10000